server:
  servlet:
    # 项目接口的上下文路径，接口前要加项目名，建议与name一致，便于区分
    context-path: /spring-boot-demo-server
  port: 8080
dubbo:
  scan:
    # dubbo 服务扫描基础包路径
    base-packages: com.personal.demo
  # dubbo所采用的协议配置
  protocol:
    id: dubbo
    # Dubbo 服务暴露的协议配置,name 为协议名称
    name: dubbo
    # port 为协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  # 用于服务消费方订阅服务提供方的应用名称的列表，若需订阅多应用，使用 "," 分割。 不推荐使用默认值为 "*"，它将订阅所有应用。
  # 这里默认使用了当前应用名，请根据需要增加对应的应用名
  cloud:
    subscribed-services: springBootDemo

# Spring数据源配置
spring:
  # 数据源配置
  datasource:
    # 启动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接路径
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=GMT%2B8&setUnicode=true&characterEncoding=utf8
    username: root
    password: root
  # Jpa相关配置
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    # 是否展示sql
    show-sql: true

  ##  redis config
  redis:
    # IP地址
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # 最大空闲连接数
        max-active: 8
        # 最小空闲连接数
        max-idle: 8
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        min-idle: 1
    # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位  1.x可以将此参数配置10000 单位是ms
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    timeout: 60s
    # 数据库设置
    database: 0

